### ISSUE TITLE
Launch-blockers

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#117]
For @camelburrito:

ALL PAGES
- [x] amp-user-notification to show cookie consent banner and block amp-analytics until accepted
- [x] include "Privacy" link in footer: https://www.google.com/intl/en/policies/privacy/
- [x] include "License" link in footer: https://github.com/ampproject/ampstart/blob/master/LICENSE
- [x] update buttons
- [x] AMPSTART.com secondary page type needs different hero. should match spec: left align, bigger secondary text than currently. "subtitle" text (size 24px, LH 32 px: [see folio](https://folio.googleplex.com/amp-kickstart/Designs/FINAL_for%20dev/AMPSTART.com#%2F0_AMP%20START%20theme.png)

LANDING PAGE
- [x] Logo should be linked to `/`
- [x] "What is AMP?" leading to a different website is confusing as the first nav point. Should be after "How it works" and before "Github"
- [x] The page templates section on the homepage looks empty on 15" screen. Make images smaller, make grey boxes extend full screen
- [x] Fix device preview so it fits on a wide screen
- [x] Templates need "Download Code" buttons
- [x] Update wordpress link (https://amphtml.wordpress.com/)  (@ericlindley-g is planning do this, but if you happen to get to it first...)
- [x] [Mobile and tablet template previews do not work in safari](https://github.com/ampproject/ampstart/issues/180)
- [x] Use final template images (when provided)
- [x] color change to match spec [(in mock up)](https://folio.googleplex.com/amp-kickstart/Designs/FINAL_for%20dev/AMPSTART.com#%2F0_ampstart_header_lc_3.png)
- [ ] remove logo in hero image - MOVED TO NEW ISSUE #244
- [x] left align content in hero
- [x] change text
- [x] update fonts: montserrat and inconsolata

COMPONENTS PAGE

- [x] Put code snippets in accordions (both mobile and desktop)
- [x] [Update iframe size to accommodate larger buttons](https://github.com/ampproject/ampstart/issues/187)
- [ ] Opening sidebar abruptly scrolls user partway down the page in iOS Chrome
- [x] Add dropshadow around nav bar iframes
- [x] Include indication of what amp-* extensions to include with each component (design below)
- [x] UI Components page: Add real images as image placeholders (I believe @spacedino is doing this)
- [x] Checkboxes + text are too close together (per https://github.com/ampproject/ampstart/issues/118)
- [x] Fix overlap issue (per https://github.com/ampproject/ampstart/issues/68)
- [x] Bug with navbar
<img width="1088" alt="screen shot 2017-02-28 at 9 14 13 am" src="https://cloud.githubusercontent.com/assets/16807766/23416132/74dd0a22-fd96-11e6-8f06-b4dcc6ae7982.png">
- [ ] swap out type "v" for chevron svg in Full Page Hero - MOVED TO NEW ISSUE #245

GET STARTED
- [x] Change page header from "How it works" to "Get started"

HOW IT WORKS
- [x] Change first sentence to match size of rest of text (not large text)

ARTICLE TEMPLATE
- [ ] add title to header - MOVED TO ISSUE #252
- [x] swap out instagram account
- [ ] add card to instagram - MOVED TO ISSUE #246
- [ ] twitter missing - MOVED TO ISSUE #247
- [ ] fix social sharing - MOVE TO ISSUE #248
- [x] swap out type "v" for chevron svg in Full Page Hero

BLOG TEMPLATE

----

For @spacedino (then to pass to @camelburrito)
ALL
- [x] add 2x images
- [ ] blog theme needs new icon, not such a drastic descender  - MOVED TO ISSUE #249
- [x] add images to instagram (1 or 3 from unsplash)

LANDING PAGE
- [x] When text is final: Provide final template images (updated content, high-res versions)
- [ ] make preview header more user friendly - MOVED TO ISSUE #250

COMPONENTS PAGE
- [x] UI Components page: Add real images as image placeholders

----

For @ericlindley-g

ALL PAGES

- [x] Scrub text

COMPONENTS PAGE
 - [ ] Add more details about how to use components - MOVE TO ISSUE #251

GET STARTED
- [x] Add more details about how to "deploy". Maybe "upload to your server or CMS" instead of "deploy"?

**Comment by spacedino** [comment]
<img width="697" alt="4a_components_add_script_tag" src="https://cloud.githubusercontent.com/assets/7339798/23388037/dd9b677a-fd14-11e6-9e6a-66bfd0c19b80.png">

**Comment by spacedino** [comment]
![image](https://cloud.githubusercontent.com/assets/7339798/23388063/f4399ac4-fd14-11e6-9bf5-d9dd7eaaba32.png)

**Comment by spacedino** [comment]
closing this. made new issues for anything that didnt get finished with a reference number. @ericlindley-g to check dupes of new ones. 

cc @camelburrito fyi
