### ISSUE TITLE
Baseline Template - Article bug punchlist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#49]
P1 (High-priority )

- [x] hero image transition from tablet to mobile is jumpy and re-centers the image. we should make this smoother. can we move the center point on tablet to match mobile crop? MOVED TO ISSUE  #325
- [x] "photo gallery" tag should match the category class from Article template (smaller, all caps, blue)
- [x] add standard spacing above drop cap section and below the line separator
- [x] line separators should be blue MOVED TO ISSUE #326
- [x] remove links on captions MOVED TO ISSUE #327
- [x] Navbar: heading jump on expand/collapse (animation at the bottom [of this doc ](https://docs.google.com/document/d/1241vqr25tCazM4CHNW6n-yIoBwWPUVz0oRb0vS89vGs/edit#)
- [x] text after carousel is doing something very strange...too small, wrong color, too much space between the elements MOVED ISSUE TO #330
- [x] lines for "Related Article" section should be aligned with the rest of the objects, not extending past them MOVED TO ISSUE #333
- [x] captions should be left align to image on desktop and indented on mobile MOVED TO ISSUE #334
- [x] social icons too big COVERED IN ISSUE #248 
- [x] fix black highlight box and spacing around text. make it even and consistent ( /to @abeck000  to provide details)
- [x] missing site title "The Scenic" > maybe we want to change this MOVED TO ISSUE #335
- [x] Update title and images to all animals ( /to @abeck000  to provide assets)
- [x] replace "read more" "v" with caret icon MOVED TO ISSUE #336
- [ ] tweak captions, should be black and grey text, no bold MOVED TO #342
- [ ] need to fix tablet view "Latest Articles" section MOVED TO ISSUE #343
- [ ] Add context to understand difference between "share" and "follow" social icons. OK FOR NOW

P2 (Medium-priority)

- [x] instagram embed should be on a card
- [x] twitter embed should be on a card

P3 (Low-priority)

- [ ] can we modify the media loader to a custom loader? ( /to @abeck000  to provide details/asset) MOVED TO ISSUE #344
- [x] add real photo credits

**Comment by abeck000** [comment]
@ericlindley-g ready for your review

**Comment by spacedino** [comment]
moved all open issues to their own ticket, closing this one.
