### ISSUE TITLE
Baseline template - Blog Post bug punchlist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#50]
P1 (High-priority)

- [ ] replace hero image with IMG_5386.jpg - MOVED TO ISSUE #315 
- [x] "Servings:" looks too small, change to body copy and highlight blue. remove ":"
- [x]  "FOOD" category tag should be all caps
- [ ] change letter spacing of h2 class = "mb4" to ".02em" - MOVED TO ISSUE #318 
- [ ] change letter spacing of h3 class ="mb4" to ".01em" - MOVED TO ISSUE #318
- [x] Navbar: heading jump on expand/collapse (animation at the bottom [of this doc ](https://docs.google.com/document/d/1241vqr25tCazM4CHNW6n-yIoBwWPUVz0oRb0vS89vGs/edit#)
- [ ] social media icons too big - MOVED TO ISSUE #319 
- [x] text in "Meet lola" section too close to image. 
- [x] text in "Meet lola" needs a full paragraph of text
- [x] instagram embed looks off, add a card to the background like the mock up
- [x] "Categories" needs margin below. "Fashion"is too close to it
- [x] "the blog" image looks off center with menu bar, may need to change this image
- [x] nav bar should only show drop shadow on scroll
- [ ] menu icon and X too big MOVED TO ISSUE #264 
- [x] spacing between side bar categories should be 40px
- [ ] "About" and "Contact" in side bar should have letter spacing of .01 rem - MOVED TO ISSUE #290
- [ ] blue for secondary categories in sidebar is too light. should match highlight blue. rollover can be lighter. MOVED TO ISUE #322
- [ ] missing blue line separators from mocks and to match Blog template - MOVED TO ISSUE #316 
- [x] "Popular articles" section looks off. Hard to tell which image is linked to which title. We might need to add description text here or add section separators ( /to @abeck000  to design: best would be a solution that works with or without description text)
- [x] Replace comments form with newsletter signup form (Leave a reply becomes an external link /to @abeck000 for designs)

P2 (Medium-priority)

- [x] comments section: name too big "ex: Rachel"
- [x] comments section: time stamp too big and wrong color "ex: 01.27.16 at 5:14 am" 
- [x] "Submit" button too small

P3 (Low-priority)

- [ ] slight jumpiness when making window smaller on images - MOVED ISSUE TO  #323
- [ ] replace "Want" section second image - MOVED TO ISSUE #324
- [x]  form fields in "leave a reply" section too crowded > we might remove this for v1 though and maybe include in components UI only if its easy...

**Comment by abeck000** [comment]
@ericlindley-g ready for your review.

**Comment by spacedino** [comment]
moved issues to other issues, closing this one.
