### ISSUE TITLE
Mobile template preview (while on mobile) - bug checklist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#55]
P1

- [ ] High-priority item 1

P2

- [ ] Medium-priority item 2

P3

- [ ] Low-priority item 3

/to @abeck000 to fill out

**Comment by spacedino** [comment]
didnt need, closing.
